---
#- name: Create pods using deployment
 # hosts: kubernetes
  #become: true
 # user: ubuntu


 # tasks:
 # - name: copying files 
   # become: true
   # copy:
  #    src: /home/ansadmin/ans/
 #     dest: /home/ubuntu/
 # - name: create a deployment
 #   command: kubectl apply -f angdeployment.yml
 # - name:
  #  command: kubectl apply -f angservice.yml
 # - name: rollout
#    command: kubectl rollout restart deployment.v1.apps/tomcat-deployment

- name: Create pods using deployment
  hosts: kubernetes
  #become: true
  user: ubuntu

  tasks:
  - name: copying files 
   # become: true
    copy:
      src: /home/ansadmin/ans/
      dest: /home/ubuntu/
  - name: Pod Creation
    command: "{{ item }}"
    with_items:
     - kubectl apply -f angdeployment.yml
     - kubectl apply -f angservice.yml
     - kubectl rollout restart deployment.v1.apps/tomcat-deployment
